// ملف مُولَّد تلقائياً - لا تعديل يدوي. تشغيل: node scripts/generate-redirects-data.js

export const explicitRedirects = new Map<string, string>([
  ["/center-alaa-al-dyn-al-tkhssy-al-tby", "/aladdin-specialized-medical-center"],
  ["/al-byrqdar-ltjarh-al-cars", "/al-byrqdar-cars"],
  ["/baik-bash-hotel-hotel-byk-bash", "/baik-bash-hotel"],
  ["/hotel-qsr-al-shhbndr-al-athry", "/shahbandar-palace-hotel"],
  ["/hospital-al-andls-al-jamay", "/al-andalus-university-hospital"],
  ["/jewellery-nbyl-_-nabils-jewelery", "/jewelry-nbyl-_-nabils-jewelery"],
  ["/company-al-mndyl-llitarat-al-aal-myh", "/al-mandeel-tires-company"],
  ["/office-khlyl-aly-ltjarh-al-cars", "/khalil-ali-cars-office"],
  ["/kindergarten-sayd-al-khash", "/saeed-private-kindergarten"],
  ["/kindergarten-st-al-wfaa", "/set-al-wafa-kindergarten"],
  ["/qhwh-al-qshlh", "/al-qashla-cafe"],
  ["/office-yasr-al-shamy", "/yasser-al-shami-cars-office"],
  ["/company-al-rstm-al-tjaryh", "/al-rustom-trading-company"],
  ["/school-al-hkmh-al-khash-yal-swydaa", "/al-hikma-private-school"],
  ["/mjmwah-al-qwafl-llshhn-al-dwly", "/al-qwafl-for-international-shipping"],
  ["/university-al-sham-al-khash-aspu-fra-al-ladhqyh", "/al-sham-private-university-latakia"],
  ["/school-sma-hwran-al-khash", "/samaa-horan-private-school"],
  ["/jewellery-al-krym", "/jewelry-al-krym"],
  ["/kindergarten-al-frh-al-khash", "/al-farah-private-kindergarten"],
  ["/kindergarten-sham-al-syah", "/sham-al-sayyah-kindergarten"],
  ["/kindergarten-al-nsha-al-jdyd", "/new-generation-kindergarten"],
  ["/syty-car", "/city-car"],
  ["/kindergarten-byty-al-dafe", "/my-warm-home-kindergarten"],
  ["/company-samr-mhrm-lqta-al-cars", "/samer-moharem-company"],
  ["/kindergarten-lma-al-sham", "/lama-al-sham-kindergarten"],
  ["/hanifa-alomar-jewelry-syria", "/hanifa-alomar-jewellery-syria"],
  ["/hospital-al-tyar-al-jrahy", "/al-tayyar-surgical-hospital"],
  ["/al-tynawy-ltajyr-al-cars", "/altayenawi-car-rental"],
  ["/office-blywn-ltjarh-al-cars", "/blion-cars-office"],
  ["/school-al-adhm-al-khash", "/al-adhm-private-school"],
  ["/kindergarten-al-shraa-al-khash", "/al-shiraa-private-kindergarten"],
  ["/jewellery-al-qwsrh", "/jewelry-al-qwsrh"],
  ["/tal-ysman-al-amyn", "/talisman-hotel"],
  ["/nswh-yasyn-llstaer-wal-mfrwshat", "/nasouh-yaseen-curtains-furniture"],
  ["/showroom-ryf-idlb-al-jnwby-zkrya-slyman", "/zakaria-suleiman-car-showroom"],
  ["/office-swryana-ltjarh-al-cars", "/souryana-cars-office"],
  ["/company-hlb-astyrad-qta-ghyar-cars-swzwky-syny", "/aleppo-car-parts-company"],
  ["/showroom-fyana-lsyarat", "/fayana-cars-showroom"],
  ["/school-w-kindergarten-abda-al-khash", "/abdaa-private-school-kindergarten"],
  ["/bnwt-lmaayrh-al-dhhb-wal-fdh", "/banout-gold-silver"],
  ["/center-al-qmh-llkmbywtr-wal-atsal-at", "/al-qimma-center"],
  ["/jewellery-lyan", "/jewelry-lyan"],
  ["/silver-lazord-midan", "/lazord-silver-midan"],
  ["/company-aal-m-al-kwry-al-tjaryh", "/korean-world-trading-company"],
  ["/office-al-mstqbl-llshhn-al-dwly", "/al-mustaqbal-international-shipping"],
  ["/hospital-faawr", "/faour-hospital"],
  ["/company-mhmd-bsam-draw", "/mohammad-bassam-daraw-company"],
  ["/mfrwshat-abw-shhadh-wawladh", "/abu-shahadeh-sons-furniture"],
  ["/aal-m-al-curtains", "/curtains-world"],
  ["/showroom-al-brkh-ltjarh-al-cars", "/al-baraka-car-showroom"],
  ["/mfrwshat-al-natwr", "/al-natour-furniture"],
  ["/company-jrks-wdhh-al-tjaryh", "/jerks-dhha-trading-company"],
  ["/al-university-al-dwlyh-llalwm-wal-tknwlwjya-iust", "/international-university-science-technology"],
  ["/hospital-al-twfyq", "/al-tawfiq-hospital"],
  ["/center-ayfa", "/eva-center"],
  ["/drmajd-mardn-dental-clinic", "/dr-majd-mardn-dental-clinic"],
  ["/showroom-al-wlyd-ltjarh-al-cars", "/al-waleed-car-showroom"],
  ["/school-al-tfwq-al-khash", "/al-tafawuq-private-highschool"],
  ["/showroom-fady-hsn-llsyarat", "/fadi-hassan-car-showroom"],
  ["/kindergarten-braam-al-aslam-al-nmwdhjyh", "/baraem-islam-kindergarten"],
  ["/kindergarten-wndrland", "/wonderland-kindergarten"],
  ["/bytza-al-ryf-al-iytal-yh", "/italian-village-pizza"],
  ["/hospital-al-kndy", "/al-kindi-hospital"],
  ["/kindergarten-al-bnfsj", "/al-banafsaj-kindergarten"],
  ["/jwd-llatarat-wmstlzmat-al-cars", "/joud-car-tires"],
  ["/hospital-al-shrq", "/al-sharq-hospital"],
  ["/kindergarten-mnarh-dmshq-al-khash", "/manarat-damascus-private-kindergarten"],
  ["/hotel-barwn", "/baron-hotel"],
  ["/hotel-bab-twma-al-athry", "/bab-touma-hotel"],
  ["/ashq-shrqy", "/eshq-sharqi"],
  ["/smart-shybyngh-lkhdmat-al-International-shipping-al-dwly-w-al-tkhlys", "/smart-shybyngh-lkhdmat-al-shhn-al-dwly-w-al-tkhlys"],
  ["/hospital-al-ashrfyh-al-tkhssy", "/al-ashrafieh-specialty-hospital"],
  ["/hospital-al-slam-al-tkhssy-bdmshq", "/al-salam-specialty-hospital-damascus"],
  ["/jewellery-al-mslmany", "/jewelry-al-mslmany"],
  ["/company-al-azy-lshhn-wtkhlys-al-customs-clearance", "/company-al-azy-lshhn-wtkhlys-al-jmrky"],
  ["/al-university-al-swryh-al-khash-spu", "/al-jamah-al-swryh-al-khash-spu"],
  ["/hospital-al-ayn-wal-adhn-al-tkhssy", "/eye-ear-specialty-hospital"],
  ["/kindergarten-shms-al-ghd-al-khash", "/kindergarten%20-shms-al-ghd-al-khash"],
  ["/school-bnah-al-ajyal-al-khash", "/bonat-al-ajyal-private-school"],
  ["/hospital-al-mna", "/al-muna-hospital"],
  ["/school-al-marfh-al-khash", "/al-maarifah-private-school"],
  ["/school-al-krml-al-khash", "/al-karamel-private-school"],
  ["/school-al-ghsanyh-al-arthwdhksyh-al-khash", "/al-ghassaniyah-private-school"],
  ["/school-al-alm-al-hdyth-al-khash", "/modern-science-private-school"],
  ["/school-al-mnhl-al-khash", "/al-manhal-private-school"],
  ["/school-dwhh-al-wrwd-al-khash", "/dawhat-al-warod-private-school"],
  ["/hotel-byt-al-wal-y", "/beit-al-wali-hotel"],
  ["/hotel-al-qsr", "/al-qasr-hotel"],
  ["/hospital-al-dyaa-al-jrahy", "/al-diaa-surgical-hospital"],
  ["/school-al-amtyaz-al-khash-alemtiaz-private-school", "/al-imtiaz-private-school"],
  ["/hospital-al-hryry", "/al-hariri-hospital"],
  ["/hotel-hms-al-kbyr", "/homs-al-kbyr-hotel"],
  ["/school-al-andls", "/al-andalus-school"],
  ["/school-al-abaa-al-arby", "/al-abaa-arabi-school"],
  ["/hospital-al-sham-al-tby", "/al-sham-medical-hospital"],
  ["/jewellery-al-aly", "/jewelry-al-aly"],
  ["/hospital-al-doctor-mhmd-dbyt", "/dr-mohamad-dbyt-hospital"],
  ["/country/sy/city/aleppo/sub-area/azaz", "/mstshfa-al-dktwr-mhmd-dbyt"],
  ["/country/sy/city/damascus/sub-area/aladawi", "/country/sy/city/aleppo/sub-area/azaz"],
  ["/hospital-al-twlyd-al-askry", "/military-maternity-hospital"],
  ["/school-al-mnarh-al-khash", "/al-manarah-private-school"],
  ["/school-al-mkhtar-al-nmwdhjyh-al-khash", "/al-mukhtar-model-private-school"],
  ["/school-al-ttbyqat-al-nmwdhjyh-al-khash", "/model-applications-private-school"],
  ["/school-al-ala-al-khash", "/al-oula-private-school"],
  ["/school-jnh-al-asafyr-al-khash", "/jannah-al-asafir-private-school"],
  ["/university-al-shhbaa-al-khash-al-mbna-al-jdyd", "/jamah-al-shhbaa-al-khash-al-mbna-al-jdyd"],
  ["/hotel-al-zhran", "/al-zahran-hotel"],
  ["/school-al-rdwan-al-khash", "/al-ridwan-private-school"],
  ["/school-ywhna-al-dmshqy-al-khash", "/yuhanna-dimashqi-private-school"],
  ["/jewellery-anwar-al-mdynh", "/jewelry-anwar-al-mdynh"],
  ["/school-al-mdynh-al-sghyrh", "/little-city-school"],
  ["/hospital-al-aasy-al-jdyd", "/new-assi-hospital"],
  ["/university-al-athad-al-khash", "/jamah-al-athad-al-khash"],
  ["/al-school-al-ywsfyh-llbnat", "/yousifiya-girls-school"],
  ["/chanel-jewelry-jewellery-shanyl", "/chanel-jewelry-mjwhrat-shanyl"],
  ["/school-al-aml-al-khash", "/al-amal-private-school"],
  ["/school-al-awdh-al-khash", "/highschool-al-awdh-al-khash"],
  ["/kindergarten-al-yasmyn-al-khash", "/kindergarten%20-al-yasmyn-al-khash"],
  ["/jewellery-al-adhm", "/jewelry-al-adhm"],
  ["/hotel-aal-bal", "/aal-bal-hotel"],
  ["/kindergarten-al-nwr-al-khash", "/hdanh-al-nwr-al-khash"],
  ["/showroom-rajw", "/mard-rajw"],
  ["/jewellery-abd-al-rhmn-hlywy", "/mswghat-abd-al-rhmn-hlywy"],
  ["/school-dmshq-al-wtnyh", "/highschool-dmshq-al-wtnyh"],
  ["/school-nwr-al-fjr", "/nour-al-fajr-school"],
  ["/jewellery-asamh", "/jewelry-asamh"],
  ["/school-al-klmh", "/al-kalima-school"],
  ["/hospital-al-asad-al-jrahy", "/al-assaad-surgical-hospital"],
  ["/kindergarten-al-ans", "/kindergarten%20-al-ans"],
  ["/hotel-lwrws", "/laurus-hotel"],
  ["/al-hospital-al-tby-al-jrahy", "/medical-surgical-hospital"],
  ["/hotel-awrba", "/europa-hotel"],
  ["/hotel-antradws", "/antradus-hotel"],
  ["/jewellery-al-jndly", "/jewelry-al-jndly"],
  ["/hotel-armtaj", "/armtage-hotel"],
  ["/hospital-al-wtn-al-khas", "/al-watan-private-hospital"],
  ["/jewellery-al-rkn-al-dhhby", "/jewelry-al-rkn-al-dhhby"],
  ["/kindergarten-asafyr-al-jnh", "/kindergarten%20-asafyr-al-jnh"],
  ["/hospital-al-tb-al-arby-al-jrahy", "/arabic-medicine-surgical-hospital"],
  ["/school-bny-tghlb-al-thanyh-al-khash", "/bani-taghleb-2-private-school"],
  ["/school-sydh-al-frh-al-khash", "/sayidat-al-farah-private-school"],
  ["/school-al-mnyr-al-talymyh-al-khash", "/al-moneer-private-school"],
  ["/school-kindergarten-al-hyaa-al-khash", "/al-hayat-private-school"],
  ["/school-al-school-al-mhsnyh-llbnyn", "/al-mohsiniya-school"],
  ["/mnzwmh-bshaer-al-ayman-school-al-rghd-al-khash", "/al-raghad-private-school"],
  ["/al-university-al-dwlyh-llmaal-jh-al-snyh-al-shamlh-wal-mjanbh", "/al-jamah-al-dwlyh-llmaal-jh-al-snyh-al-shamlh-wal-mjanbh"],
  ["/dndnh-cafe", "/dndnh-kafyh"],
  ["/hospital-al-razy-al-jdyd", "/al-razy-new-hospital"],
  ["/almashreq-hospital-hospital-al-mshrq", "/almashreq-hospital"],
  ["/school-jyl-al-ghd-al-khash", "/jil-al-ghad-private-school"],
  ["/al-school-al-amrykyh", "/american-school"],
  ["/hospital-al-astshary-al-hdyth", "/modern-consulting-hospital"],
  ["/hospital-dar-al-aywn-wal-tjmyl", "/dar-aloyoun-cosmetic-hospital"],
  ["/school-shms-al-maarf-al-khash", "/shams-al-maaref-private-school"],
  ["/hospital-bdya-hmwdh-al-jrahy", "/badea-hamoudeh-surgical-hospital"],
  ["/jewellery-dhkryat", "/jewelry-dhkryat"],
  ["/hotel-byt-al-mmlwkh", "/fbeit-al-mamloukeh-hotel"],
  ["/hospital-al-raayh-al-khash", "/al-rayah-private-hospital"],
  ["/kindergarten-al-rshyd", "/kindergarten%20-al-rshyd"],
  ["/school-al-aasyh-al-khash", "/al-asiya-private-school"],
  ["/hotel-brj-al-shahyn", "/burj-al-shahyn-hotel"],
  ["/hospital-al-ahram-al-tkhssy", "/al-ahram-specialty-hospital"],
  ["/school-al-frh-al-khash", "/al-farah-private-school"],
  ["/jewellery-al-ghrywaty-lldhhb", "/jewelry-al-ghrywaty-lldhhb"],
  ["/school-mahd-al-njah-al-khash-llbnat", "/highschool-mahd-al-njah-al-khash-llbnat"],
  ["/sham-lltaqh-al-solar-wal-btaryat", "/sham-lltaqh-al-shmsyh-wal-btaryat"],
  ["/kindergarten-al-mshaal", "/kindergarten%20-al-mshaal"],
  ["/kindergarten-njwm-al-ghd", "/kindergarten%20-njwm-al-ghd"],
  ["/hospital-al-aysa", "/al-ayssa-hospital"],
  ["/hotel-qsr-al-shrq", "/qasr-al-sharq-hotel"],
  ["/jewellery-bsam-tamh", "/jewelry-bsam-tamh"],
  ["/hospital-al-mdynh", "/al-madina-hospital"],
  ["/mktbauto-bazar", "/officeauto-bazar"],
  ["/company-al-hyah-lltkhlys-al-customs-clearance-wal-nql-al-arby-wal-dwly", "/company-al-hyah-lltkhlys-al-jmrky-wal-nql-al-arby-wal-dwly"],
  ["/school-al-amal-al-rafdh-al-khash", "/alamal-alrafedah-private-school"],
  ["/hotel-al-dywan", "/al-diwan-hotel"],
  ["/school-al-amyn-al-khash", "/al-ameen-private-school"],
  ["/hospital-bshyr-aalajaty-lltwlyd", "/bashir-maternity-hospital"],
  ["/hotel-amyh", "/omyah-hotel"],
  ["/jewellery-abyd-w-sman", "/jewelry-abyd-w-sman"],
  ["/al-school-al-hdythh-al-khash", "/al-hadythh-private-school"],
  ["/hotel-antyk-khan", "/antique-khan-hotel"],
  ["/jewellery-byt-al-dhhb", "/jewelry-byt-al-dhhb"],
  ["/jewellery-jbwly", "/jewelry-jbwly"],
  ["/school-al-aml-al-khash-1", "/al-amal-private-school-1"],
  ["/school-al-awj-al-khash", "/al-awj-private-school"],
  ["/school-iylaf-al-khash", "/ilaf-private-school"],
  ["/h-house-hotel-hotel-byt-al-jwd-wal-krm", "/beit-al-joud-wal-karam-hotel"],
  ["/hospital-al-amyn-al-tkhssy", "/al-ameen-specialty-hospital"],
  ["/jewellery-al-zyn", "/jewelry-al-zyn"],
  ["/hotel-aylya-al-syahy", "/aylya-touristic-hotel"],
  ["/hospital-al-kindergarten-al-jrahy", "/al-rawda-surgical-hospital"],
  ["/hotel-inana", "/inana-hotel"],
  ["/hotel-zyn-blas", "/zain-plase-hotel"],
  ["/hospital-al-shfaa", "/al-shifa-hospital"],
  ["/school-al-msawdyh-al-khash", "/masoudiya-private-school"],
  ["/hospital-al-jsry", "/al-jasry-hospital"],
  ["/kindergarten-al-njwm", "/kindergarten%20-al-njwm"],
  ["/jewellery-abnaa-nwr-al-dyn", "/jewelry-abnaa-nwr-al-dyn"],
  ["/school-al-mawnh-al-khash-llinath", "/al-mawneh-girls-private-school"],
  ["/jewellery-jewellery-ahmd-sbhy-hlywy", "/mswghat-mswghat-ahmd-sbhy-hlywy"],
  ["/store-mhmd-hsham-al-khdry", "/mhl-mhmd-hsham-al-khdry"],
  ["/kindergarten-al-njwm-al-khash", "/kindergarten%20-al-njwm-al-khash"],
  ["/school-shate-al-atfal-al-khash-shatea-alatfal-school", "/shatea-al-atfal-private-school"],
  ["/hospital-al-sbyl-al-tkhssy-al-jrahy", "/al-sabeel-specialty-surgical-hospital"],
  ["/jewellery-al-mash", "/jewelry-al-mash"],
  ["/school-mnahl-al-khyrat-al-khash", "/manahil-al-khayrat-private-school"],
  ["/school-al-khtwh-al-awla", "/first-step-school"],
  ["/school-dwhh-al-rhab", "/dawhat-al-rahab-school"],
  ["/school-abjdyh-al-ghryb-al-khash", "/abjadiyat-al-gharib-private-school"],
  ["/al-hospital-al-swry-al-frnsy-al-tkhssy", "/syrian-french-specialty-hospital"],
  ["/school-al-awael-al-nmwdhjyh-al-khash-llbnat", "/al-awail-model-girls-private-school"],
  ["/hospital-al-twlyd-al-khas", "/private-maternity-hospital"],
  ["/school-al-sham-al-nmwdhjyh-al-khash-llbnyn", "/highschool-al-sham-al-nmwdhjyh-al-khash-llbnyn"],
  ["/school-al-jmhwr-al-khash-llinath", "/al-jumhour-girls-private-school"],
  ["/al-hospital-al-arby-al-jdyd", "/new-arabic-hospital"],
  ["/shamo-jewellery-jewellery-shamw", "/shamo-jewellery-mjwhrat-shamw"],
  ["/cole-prive-al-riaya-school-al-raayh-al-khash", "/al-riaya-private-school"],
  ["/school-al-sydh-mrym-al-khash", "/sayyidah-maryam-private-school"],
  ["/center-al-andls-llalwm-al-syahyh", "/mrkz-al-andls-llalwm-al-syahyh"],
  ["/al-hospital-al-ahly-al-tkhssy", "/al-ahly-specialty-hospital"],
  ["/school-abn-khldwn-al-khash", "/ibn-khaldoun-private-school"],
  ["/nwr-lltqnyat-al-khrbaeyh-wal-solar-al-solar", "/nwr-lltqnyat-al-khrbaeyh-wal-taqh-al-shmsyh"],
  ["/school-al-zhraa-al-khash-al-martyny", "/al-zahraa-private-school"],
  ["/hospital-al-hyah", "/al-hayat-hospital"],
  ["/school-al-qryh-al-sghyrh", "/little-village-school"],
  ["/al-hospital-al-swry-al-tkhssy", "/syrian-specialty-hospital"],
  ["/al-university-al-arbyh-al-khash-llalwm-wal-tknwlwjya", "/al-jamah-al-arbyh-al-khash-llalwm-wal-tknwlwjya"],
  ["/jewellery-hsn", "/jewelry-hsn"],
  ["/hospital-al-abasyh", "/al-abbasiyah-hospital"],
  ["/hospital-al-zaym-al-tkhssy", "/al-zaaim-specialty-hospital"],
  ["/jewellery-hlb", "/mswghat-hlb"],
  ["/kindergarten-nbras-al-marfh", "/kindergarten%20-nbras-al-marfh"],
  ["/school-dwhh-al-trbyh-al-khash", "/dawhat-al-tarbiyah-private-school"],
  ["/school-jabr-al-ansary-khash", "/jabr-al-ansari-private-school"],
  ["/school-arwad-al-khash", "/arwad-private-school"],
  ["/school-al-anayh-al-khash", "/al-inayah-private-school"],
  ["/hospital-smart-kyr-al-tkhssy-smart-care-hospital", "/smart-care-specialty-hospital"],
  ["/school-al-mkhtar-al-nmwdhjyh", "/al-mukhtar-model-school"],
  ["/school-fjr-al-tfwq-al-khash", "/fajr-al-tafoq-private-school"],
  ["/hotel-al-aamr", "/al-aamer-hotel"],
  ["/hotel-bsman", "/basman-hotel"],
  ["/hotel-qsr-al-fars", "/qasr-al-fares-hotel"],
  ["/school-aafaq-al-sham-al-khashinath", "/afaq-al-sham-private-school"],
  ["/kindergarten-al-martqla", "/kindergarten%20-al-martqla"],
  ["/jewellery-dha", "/jewelry-dha"],
  ["/school-al-njah-al-khash", "/al-najah-private-school"],
  ["/al-hospital-al-swry", "/alsouri-hospital"],
  ["/hospital-al-nwr-lltwlyd", "/al-noor-maternity-hospital"],
  ["/hospital-al-rshyd", "/al-rasheed-hospital"],
  ["/hotel-al-bhr-bls", "/bahr-plase-hotel"],
  ["/hospital-bysan", "/baysan-hospital"],
  ["/hotel-trtws-al-kbyr", "/tartous-grand-hotel"],
  ["/hospital-al-hkmh", "/hikma-hospital"],
  ["/school-dar-al-slam", "/dar-al-salam-school"],
  ["/hospital-al-asdy", "/al-asady-hospital"],
  ["/jewellery-wmswghat-kfa", "/jewelry-wmswghat-kfa"],
  ["/school-alya-al-khask", "/aliya-private-school"],
  ["/jewellery-brkat", "/jewelry-brkat"],
  ["/school-dar-al-naym", "/dar-al-naeem-school"],
  ["/hospital-al-ahly", "/alahly-hospital"],
  ["/hospital-al-shhbaa-al-tkhssy", "/al-shahbaa-specialty-hospital"],
  ["/hospital-al-fyhaa", "/fayhaa-hospital"],
  ["/hospital-al-shamy", "/al-shami-hospital"],
  ["/kindergarten-w-school-al-ibdaa-al-khash", "/al-ibdaa-private-kindergarten-school"],
  ["/hospital-al-gas-station", "/al-mahath-hospital"],
  ["/hospital-amyh", "/omyah-hospital"],
  ["/hotel-al-qysr", "/al-qaysar-hotel"],
  ["/hotel-al-sal-h", "/al-salih-hotel"],
  ["/al-hospital-al-iytal-y", "/italian-hospital"],
  ["/jewellery-t", "/jewelry-t"],
  ["/office-al-jrjnazy-lajar-al-cars", "/office-al-jrjnazy-lajar-al-syarat"],
  ["/kindergarten-al-qswr-al-ahlyh", "/kindergarten%20-al-qswr-al-ahlyh"],
  ["/hospital-hsn-shykh-al-ard-al-tkhssy", "/hassan-sheikh-alard-specialty-hospital"],
  ["/jewellery-smyr", "/jewelry-smyr"],
  ["/kindergarten-al-aml-al-khash-1", "/kindergarten%20-al-aml-al-khash-1"],
  ["/hospital-al-qdys-lwys-al-frnsy", "/saint-louis-french-hospital"],
  ["/dar-al-noor-hotel-hotel-dar-al-nwr", "/dar-al-noor-hotel"],
  ["/hotel-al-btraa", "/al-batraa-hotel"],
  ["/hotel-dywnyzyas", "/dionysias-hotel"],
  ["/jewellery-wmswghat-al-hwrany", "/jewelry-wmswghat-al-hwrany"],
  ["/kindergarten-snabl-al-khyr", "/kindergarten%20-snabl-al-khyr"],
  ["/showroom-zkrya", "/mard-zkrya"],
  ["/jewellery-al-wlaa", "/jewelry-al-wlaa"],
  ["/al-school-al-ahlyh-al-khash-astfan", "/al-thanwyh-al-ahlyh-al-khash-astfan"],
  ["/school-al-abdaa-al-khash", "/al-ebdaa-private-school"],
  ["/school-dwhh-al-blabl", "/dawhat-al-balabel-school"],
  ["/hospital-al-sydh-al-jrahy", "/al-saydeh-surgical-hospital"],
  ["/kindergarten-roa-al-mstqbl", "/kindergarten%20-roa-al-mstqbl"],
  ["/university-al-sham-al-khash-aspu", "/jamah-al-sham-al-khash-aspu"],
  ["/company-alma-lltkhlys-al-customs-clearance", "/company-alma-lltkhlys-al-jmrky"],
  ["/jewellery-al-shryqy", "/jewelry-al-shryqy"],
  ["/school-al-tlyah-al-khash-bdmshq", "/al-talia-private-school-damascus"],
  ["/showroom-abad-al-rhmn", "/mard-abad-al-rhmn"],
  ["/hospital-al-rhmh", "/al-rahma-hospital"],
  ["/hospital-tshryn-al-jamay", "/tishreen-university-hospital"],
  ["/hotel-al-hdyqh", "/al-hadiqa-hotel"],
  ["/jewellery-hydr", "/jewelry-hydr"],
  ["/hospital-al-razy", "/al-razy-hospital"],
  ["/hotel-tdmr", "/tadmor-hotel"],
  ["/hotel-sfyr-hms", "/safir-homs-hotel"],
  ["/company-International-shipping-al-hythm", "/company-shhn-al-hythm"],
  ["/kindergarten-wmdrsh-al-nwr-al-khash", "/al-noor-private-kindergarten-school"],
  ["/jewellery-al-bdwy", "/jewelry-al-bdwy"],
  ["/showroom-tftnaz", "/mard-tftnaz"],
  ["/kindergarten-shmws-al-ghd", "/kindergarten%20-shmws-al-ghd"],
  ["/kindergarten-al-kwkh", "/kindergarten%20-al-kwkh"],
  ["/hotel-klasykal", "/classical-hotel"],
  ["/kindergarten-braam-al-ghfran", "/kindergarten%20-braam-al-ghfran"],
  ["/hotel-abw-al-kmyt", "/abu-al-kamit-hotel"],
  ["/hospital-al-mwasah", "/al-muwasat-hospital"],
  ["/kindergarten-yasmyn-al-sham", "/kindergarten%20-yasmyn-al-sham"],
  ["/hospital-al-amwry", "/al-amouri-hospital"],
  ["/showroom-ahmd-rmdan", "/mard-ahmd-rmdan"],
  ["/jewellery-mswh", "/jewelry-mswh"],
  ["/kindergarten-al-rwaby", "/kindergarten%20-al-rwaby"],
  ["/kindergarten-al-snabl-al-fra-al-awl", "/kindergarten%20-al-snabl-al-fra-al-awl"],
  ["/showroom-mrhf-hdad", "/mard-mrhf-hdad"],
  ["/kindergarten-al-hkmh", "/kindergarten%20-al-hkmh"],
  ["/kindergarten-al-nda", "/kindergarten%20-al-nda"],
  ["/kassabian-company-company-qsabyan", "/kassabian-company-shrkh-qsabyan"],
  ["/kindergarten-dyzny-kydz", "/kindergarten%20-dyzny-kydz"],
  ["/hotel-sarh", "/sarah-hotel"],
  ["/showroom-al-hbal", "/mard-al-hbal"],
  ["/knq-al-cars", "/knq-al-syarat"],
  ["/hospital-al-mjd", "/al-majd-hospital"],
  ["/kindergarten-al-wfaa", "/kindergarten%20-al-wfaa"],
  ["/kindergarten-frdw", "/kindergarten%20-frdw"],
  ["/kindergarten-al-ala", "/kindergarten%20-al-ala"],
  ["/jewellery-al-mhbh", "/jewelry-al-mhbh"],
  ["/kindergarten-al-mamwn", "/kindergarten%20-al-mamwn"],
  ["/hospital-al-slam", "/al-salam-hospital"],
  ["/jewellery-kmal", "/jewelry-kmal"],
  ["/hospital-dar-al-shfaa", "/dar-alshifa-hospital"],
  ["/jewellery-asamh-aaram", "/jewelry-asamh-aaram"],
  ["/hospital-al-shqqy", "/al-sheqaqi-hospital"],
  ["/jewellery-dhby-wagha", "/jewelry-dhby-wagha"],
  ["/hospital-al-mal-k", "/al-malek-hospital"],
  ["/jewellery-jbran", "/mswghat-jbran"],
  ["/mdrshetc-al-khash", "/etc-private-school"],
  ["/kindergarten-dar-al-mrh", "/kindergarten%20-dar-al-mrh"],
  ["/kindergarten-shamna", "/kindergarten%20-shamna"],
  ["/kindergarten-al-nwr", "/kindergarten%20-al-nwr"],
  ["/kindergarten-tshryn", "/kindergarten%20-tshryn"],
  ["/jewellery-rtyl", "/jewelry-rtyl"],
  ["/kindergarten-azhar-al-bnfsj", "/kindergarten%20-azhar-al-bnfsj"],
  ["/school-djlh-al-khash", "/dajla-private-school"],
  ["/kindergarten-snabl-al-tfwlh", "/kindergarten%20-snabl-al-tfwlh"],
  ["/kindergarten-aafaq-al-tfwlh", "/kindergarten%20-aafaq-al-tfwlh"],
  ["/kindergarten-drwb-al-nwr", "/kindergarten%20-drwb-al-nwr"],
  ["/caramel-preschool-kindergarten-karamyl", "/caramel-preschool-rwdh-karamyl"],
  ["/kindergarten-al-snabl-al-fra-al-thany", "/kindergarten%20-al-snabl-al-fra-al-thany"],
  ["/kindergarten-kmal-al-tfwlh", "/kindergarten%20-kmal-al-tfwlh"],
  ["/kindergarten-ahlam-al-tfwlh", "/kindergarten%20-ahlam-al-tfwlh"],
  ["/kindergarten-drym-land", "/kindergarten%20-drym-land"],
  ["/kindergarten-al-nkhyl", "/kindergarten%20-al-nkhyl"],
  ["/hospital-al-hwrany", "/hawrani-hospital"],
  ["/country/sy/category/restaurants/cafes", "/country/sy/category/restaurants/caf%C3%A9s"],
  ["/kindergarten-nwr-al-ajyal", "/kindergarten%20-nwr-al-ajyal"],
  ["/school-mary-al-khash", "/mary-private-school"],
  ["/kindergarten-mama-nbyla", "/kindergarten%20-mama-nbyla"],
  ["/rasal-ltjarh-al-cars", "/rasal-ltjarh-al-syarat"],
  ["/jewellery-mtya", "/jewelry-mtya"],
  ["/showroom-zaza", "/mard-zaza"],
  ["/kindergarten-dar-al-krm", "/kindergarten%20-dar-al-krm"],
  ["/kindergarten-mdynh-al-atfal", "/kindergarten%20-mdynh-al-atfal"],
  ["/hospital-al-mzrah", "/al-mazraah-hospital"],
  ["/jewellery-al-rfaay-2", "/jewelry-al-rfaay-2"],
  ["/university-bshyr-rhyjh", "/jamah-bshyr-rhyjh"],
  ["/kindergarten-bshaer-al-iyman", "/kindergarten%20-bshaer-al-iyman"],
  ["/jewellery-al-aamyn", "/jewelry-al-aamyn"],
  ["/kindergarten-al-zhwr", "/kindergarten%20-al-zhwr"],
  ["/kindergarten-al-frqan", "/kindergarten%20-al-frqan"],
  ["/kindergarten-bably-land", "/hdanh-bably-land"],
  ["/qbany-lqta-ghyar-al-cars", "/qbany-lqta-ghyar-al-syarat"],
  ["/hospital-al-bdr-al-tkhssy", "/al-badr-specialty-hospital"],
  ["/hospital-d-nasr-shqyr", "/dr-nasser-shuqair-hospital"],
  ["/kindergarten-snabl-al-nyrb", "/kindergarten%20-snabl-al-nyrb"],
  ["/kindergarten-tlaea-jrmana", "/kindergarten%20-tlaea-jrmana"],
  ["/kindergarten-ajyal-al-khash", "/kindergarten%20-ajyal-al-khash"],
  ["/kindergarten-frdws-al-atfal", "/kindergarten%20-frdws-al-atfal"],
  ["/kindergarten-dwhh-al-sghar", "/kindergarten%20-dwhh-al-sghar"],
  ["/jewellery-mlwhy", "/jewelry-mlwhy"],
  ["/kindergarten-bhr-al-alwm", "/kindergarten%20-bhr-al-alwm"],
  ["/hospital-al-mtlq", "/al-mutlaq-hospital"],
  ["/jewellery-wmjwhrat-krwma", "/mswghat-wmjwhrat-krwma"],
  ["/jewellery-al-basha", "/jewelry-al-basha"],
  ["/kindergarten-braam-al-aqsa", "/kindergarten%20-braam-al-aqsa"],
  ["/hospital-al-zhrawy", "/al-zhrawi-hospital"],
  ["/jewellery-al-jblawy", "/jewelry-al-jblawy"],
  ["/jewellery-abrahym-bsath-wawladh", "/jewelry-abrahym-bsath-wawladh"],
  ["/hospital-al-razy-al-jrahy-al-hdyth", "/al-razy-modern-surgical-hospital"],
  ["/jewellery-ywsf", "/jewelry-ywsf"],
  ["/al-hospital-al-mrkzy", "/al-markazi-hospital"],
  ["/hospital-al-tabyat-al-jrahy", "/al-ttabyatt-surgical-hospital"],
  ["/hospital-al-twlyd-wal-atfal", "/maternity-children-hospital"],
  ["/al-hospital-al-wtny", "/national-hospital"],
  ["/dr-oussama-haroun-hospital-hospital-al-doctor-asamh-harwn", "/dr-oussama-haroun-hospital"],
  ["/hospital-al-bshyr-al-jrahy", "/al-basheer-surgical-hospital"],
  ["/jewellery-bysan", "/mswghat-bysan"],
  ["/hospital-al-mhayny", "/al-mhayni-hospital"],
  ["/cafe-al-hsn", "/kafyh-al-hsn"],
  ["/hotel-brj-al-mstqbl", "/burj-al-mustaqbal-hotel"],
  ["/country/sy/city/damascus/sub-area/alqaymarya/category/restaurants", "/country/sy/city/damascus/sub-area/%D8%B4%D8%A7%D8%B1%D8%B9-%D8%A7%D9%84%D9%82%D9%8A%D9%85%D8%B1%D9%8A%D8%A9/category/restaurants"],
  ["/hospital-zahy-azrq-al-askry", "/zahi-azraq-military-hospital"],
  ["/jewellery-wmswghat-al-tamh", "/jewelry-wmswghat-al-tamh"],
  ["/jewellery-frfshh-plus", "/mswghat-frfshh-plus"],
  ["/hospital-al-haj-sal-h", "/hajj-salah-hospital"],
  ["/jewellery-wmjwhrat-mladh", "/mswghat-wmjwhrat-mladh"],
  ["/jewellery-wmjwhrat-lylas", "/mswghat-wmjwhrat-lylas"],
  ["/school-rwafd", "/rawafed-school"],
  ["/hospital-al-ashtr", "/al-ashtar-hospital"],
  ["/hotel-al-majd", "/al-majd-hotel"],
  ["/jewellery-bqlh", "/jewelry-bqlh"],
  ["/school-dwhh-al-mjd", "/dawhat-al-majd-school"],
  ["/store-lamas-llmjwhrat", "/mhl-lamas-llmjwhrat"],
  ["/jewellery-alaa-jbdwn", "/mswghat-alaa-jbdwn"],
  ["/jewellery-nmyr-aadl-hydr", "/jewelry-nmyr-aadl-hydr"],
  ["/awak-jewelery-jewellery-awk", "/awak-jewelery-mswghat-awk"],
  ["/jewellery-twmajan", "/jewelry-twmajan"],
  ["/jewellery-al-khyr", "/jewelry-al-khyr"],
  ["/hotel-brj-al-frdws", "/burj-al-firdaws-hotel"],
  ["/hotel-wmntja-lamyra", "/lamira-resort-hotel"],
  ["/jewellery-al-syd", "/jewelry-al-syd"],
  ["/hotel-arman-arman", "/arman-hotel"],
  ["/jewellery-al-khyat", "/jewelry-al-khyat"],
  ["/hotel-al-aywan", "/al-aywan-hotel"],
  ["/hotel-ghzal", "/ghazal-hotel"],
  ["/jewellery-ahmd-ghndwr", "/jewelry-ahmd-ghndwr"],
  ["/hotel-bwabh-al-shrq", "/bawwabet-al-sharq-hotel"],
  ["/hotel-rygha", "/raygha-hotel"],
  ["/school-kindergarten-al-kwn-al-khash", "/rowdat-al-kawn-private-school"],
  ["/jewellery-rnd", "/jewelry-rnd"],
  ["/jewellery-th", "/jewelry-th"],
  ["/hotel-al-sfyr", "/al-safir-hotel"],
  ["/jewellery-mrhf-bnyan", "/jewelry-mrhf-bnyan"],
  ["/jewellery-tybh-fra-2", "/jewelry-tybh-fra-2"],
  ["/school-al-saadh-al-khash", "/highschool-al-saadh-al-khash"],
  ["/school-al-amyrkan", "/american-private-school"],
  ["/hotel-ramyta", "/ramyta-hotel"],
  ["/ghna-jewellery-tqlydyh", "/ghna-mjwhrat-tqlydyh"],
  ["/jewellery-sabr", "/jewelry-sabr"],
  ["/jewellery-abdllh-jbdwn", "/mswghat-abdllh-jbdwn"],
  ["/hotel-shhbaa-hlb", "/shahbaa-aleppo-hotel"],
  ["/jewellery-lyn-leen-jewelleries", "/jewelry-lyn-leen-jewelleries"],
  ["/hotel-kwyn-sntr", "/queen-center-hotel"],
  ["/school-mshaal-al-sham-al-khash", "/mshaal-al-sham-private-school"],
  ["/hospital-al-aryan", "/al-aryan-hospital"],
  ["/jewellery-al-ghdq-alghadaq", "/jewelry-al-ghdq-alghadaq"],
  ["/jewellery-yzn-al-tshh", "/jewelry-yzn-al-tshh"],
  ["/jewellery-mazn-adymh", "/jewelry-mazn-adymh"],
  ["/school-al-awael-llbnat-fra-al-akrm", "/al-awail-girls-school-akram"],
  ["/hospital-aysa", "/aissa-hospital"],
  ["/jewellery-tyfany-tiffany", "/jewelry-tyfany-tiffany"],
  ["/hotel-dama-rwz", "/dama-rose-hotel"],
  ["/hospital-al-rjaa", "/al-rajaa-hospital"],
  ["/hospital-al-andls", "/al-andalus-hospital"],
  ["/hospital-mzlwmyan", "/mazlomyan-hospital"],
  ["/hotel-al-mdynh", "/al-madina-hotel"],
  ["/hospital-al-braam", "/al-baram-hospital"],
  ["/hospital-jrmana-al-jrahy", "/jaramana-surgical-hospital"],
  ["/school-dmshq-al-arbyh", "/highschool-dmshq-al-arbyh"],
  ["/jewellery-mash", "/jewelry-mash"],
  ["/hotel-al-slam", "/al-salam-hotel"],
  ["/school-al-dar-al-talymyh-al-khash", "/aldar-altaalimia-private-school"],
  ["/hospital-al-nwr", "/al-nour-hospital"],
  ["/jewellery-mshlh", "/mswghat-mshlh"],
  ["/jewellery-adnan", "/jewelry-adnan"],
  ["/school-al-hkmh", "/al-hikmah-school"],
  ["/jewellery-ghadh-gada-jewelry", "/jewelry-ghadh-gada-jewelry"],
  ["/jewellery-abnaa-mamwn-al-rfaay", "/jewelry-abnaa-mamwn-al-rfaay"],
  ["/jewellery-qfaf", "/jewelry-qfaf"],
  ["/hotel-al-jlaa", "/al-jalaa-hotel"],
  ["/hospital-al-tb-al-hdyth", "/modern-medicine-hospital"],
  ["/hotel-harwn", "/haroun-hotel"],
  ["/hotel-al-sham", "/al-sham-hotel"],
  ["/jewellery-al-mlkh", "/jewelry-al-mlkh"],
  ["/hotel-dmshq-al-dwly", "/damascus-international-hotel"],
  ["/hotel-shyratwn-hlb", "/sheraton-aleppo-hotel"],
  ["/hotel-afamya", "/afamia-hotel"],
  ["/hotel-blw-tawr", "/blue-tower-hotel"],
  ["/jewellery-sarh-sara-jewelery", "/jewelry-sarh-sara-jewelery"],
  ["/kindergarten-al-tfwq-al-nmwdhjyh", "/kindergarten%20-al-tfwq-al-nmwdhjyh"],
  ["/hotel-rwyal-smyramys", "/royal-semiramis-hotel"],
  ["/hotel-al-rbya", "/al-rabea-hotel"],
  ["/hotel-qsr-hlb", "/qasr-aleppo-hotel"],
  ["/hospital-frkwh", "/farkuh-hospital"],
  ["/jewellery-al-ghmyan", "/jewelry-al-ghmyan"],
  ["/jewellery-al-brhm", "/jewelry-al-brhm"],
  ["/hotel-mdynh-al-yasmyn", "/yasmin-city-hotel"],
  ["/hotel-al-zytwnh", "/al-zaytouna-hotel"],
  ["/kindergarten-amyh-al-khash", "/kindergarten%20-amyh-al-khash"],
  ["/jewellery-kmwz-amany", "/jewelry-kmwz-amany"],
  ["/hotel-fynysya", "/vinisia-hotel"],
  ["/hotel-znwbya", "/zenobia-hotel"],
  ["/hotel-karltwn", "/carlton-hotel"],
  ["/jewellery-slyman-slamh", "/jewelry-slyman-slamh"],
  ["/hotel-shhryar", "/shahriar-hotel"],
  ["/jewelryhanifa-jewellery-hyfh", "/jewelryhanifa-mjwhrat-hyfh"],
  ["/hospital-al-swfy", "/al-soufi-hospital"],
  ["/hospital-nwr-al-aabdyn", "/noor-al-abedin-hospital"],
  ["/hospital-alaj-al-srtan", "/cancer-treatment-hospital"],
  ["/zryab-cafe", "/zryab-kafyh"],
  ["/hospital-draj", "/daraj-hospital"],
  ["/hospital-bhrw-al-nsaey", "/bahro-gynecology-hospital"],
  ["/hospital-al-nda", "/al-nada-hospital"],
]);

export const slugReplacements: { from: string; to: string }[] = [
  { from: "kafyh", to: "cafe" },
  { from: "kar", to: "car" },
  { from: "syarat", to: "cars" },
  { from: "mrkz", to: "center" },
  { from: "llalbsh", to: "clothing" },
  { from: "azyaa", to: "clothing" },
  { from: "mlbwsat", to: "clothing" },
  { from: "shrkh", to: "company" },
  { from: "hwasyb", to: "computers" },
  { from: "kmbywtr", to: "computers" },
  { from: "staer", to: "curtains" },
  { from: "jmrky", to: "customs-clearance" },
  { from: "asnan", to: "dental-clinic" },
  { from: "qyadh", to: "driving-school" },
  { from: "kazyh", to: "gas-station" },
  { from: "mhrwqat", to: "gas-station" },
  { from: "mhth", to: "gas-station" },
  { from: "nady", to: "gym" },
  { from: "mshfa", to: "hospital" },
  { from: "mstshfa", to: "hospital" },
  { from: "fndq", to: "hotel" },
  { from: "shhn", to: "International-shipping" },
  { from: "mjwhrat", to: "jewellery" },
  { from: "mswghat", to: "jewellery" },
  { from: "hdanh", to: "kindergarten" },
  { from: "rwdh", to: "kindergarten" },
  { from: "mktb", to: "office" },
  { from: "atwr", to: "parfum" },
  { from: "tswyr", to: "photography" },
  { from: "aqarat", to: "real-estate" },
  { from: "aqaryh", to: "real-estate" },
  { from: "mdars", to: "school" },
  { from: "mdrsh", to: "school" },
  { from: "thanwyh", to: "school" },
  { from: "hdhaa", to: "shoes" },
  { from: "llahdhyh", to: "shoes" },
  { from: "shwz", to: "shoes" },
  { from: "mard", to: "showroom" },
  { from: "shmsyh", to: "solar" },
  { from: "taqh", to: "solar" },
  { from: "sbwrat", to: "sporat" },
  { from: "mlab", to: "stadium" },
  { from: "mhl", to: "store" },
  { from: "stwdyw", to: "studio" },
  { from: "tksy", to: "taxi" },
  { from: "tknwlwjy", to: "technology" },
  { from: "jamah", to: "university" },
  { from: "ayadh", to: "clinic" },
  { from: "mswr", to: "photography" },
  { from: "dktwr", to: "doctor" },
  { from: "mfrwshat", to: "furniture" },
];
